{
 "title": "boutiquessj",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "label": "Deployment", "query": "boutiquessj" },
   { "name": "interval", "query": "1m" },
   {
    "name": "deploy",
    "label": "Deployment",
    "query": {
     "query": "query_result((sum(istio_requests_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_requests_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)) or (sum(istio_tcp_sent_bytes_total{destination_workload_namespace=~\"$namespace\"}) by (destination_workload) or sum(istio_tcp_sent_bytes_total{source_workload_namespace=~\"$namespace\"}) by (source_workload)))"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Load",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "reqps" }
   ],
   "targets": [
    {
     "expr": "sum(rate(istio_requests_total{destination_workload_namespace=~\"$namespace\",reporter='destination',destination_workload=~\"$deploy\"}[$interval]))",
     "legendFormat": "Request(每秒处理请求数)"
    },
    {
     "expr": "100-((sum(rate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$deploy\",response_code=\"200\"}[$interval]))+sum(rate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$deploy\",response_code=\"302\"}[$interval])))/sum(rate(istio_requests_total{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$deploy\"}[$interval])))*100",
     "legendFormat": "Error Rate"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(irate(container_cpu_usage_seconds_total{container=~\"$deploy.*\",namespace=~\"$namespace\"}[5m])*100)/sum(container_spec_cpu_quota{container=~\"$deploy.*\",namespace=~\"$namespace\"}/container_spec_cpu_period{container=~\"$deploy.*\",namespace=~\"$namespace\"})",
     "legendFormat": "testCPU"
    }
   ]
  },
  {
   "title": "Response Time",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "clockms" } },
   "targets": [
    {
     "expr": "sum(rate(istio_request_duration_milliseconds_sum{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$deploy\"}[$interval]))/sum(rate(istio_request_duration_milliseconds_count{destination_workload_namespace=~\"$namespace\",destination_workload=~\"$deploy\"}[$interval]))",
     "legendFormat": "res"
    },
    {
     "expr": "histogram_quantile(0.90, sum(irate(istio_request_duration_milliseconds_bucket{destination_workload_namespace=~\"$namespace\", destination_workload=~\"$deploy\"}[$interval])) by (le))",
     "legendFormat": "p90"
    }
   ]
  },
  {
   "title": "Memory",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 6 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",container=~\"$deploy\"})",
     "legendFormat": "Usage"
    },
    {
     "expr": "sum(container_memory_usage_bytes{namespace=~\"$namespace\",container=~\"$deploy\"}) / sum(container_spec_memory_limit_bytes{namespace=~\"$namespace\",container=~\"$deploy\"}) * 100",
     "legendFormat": "Utilization"
    }
   ]
  },
  {
   "title": "Replicas",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "count(container_spec_cpu_period{namespace=~\"$namespace\",container=~\"$deploy\"})",
     "legendFormat": "Pod"
    },
    {
     "expr": "count(sum(rate(container_cpu_usage_seconds_total{image!=\"\",namespace=~\"$namespace\", container=~\"$deploy\"}[$interval])) by (pod, namespace))",
     "legendFormat": "p"
    }
   ]
  },
  {
   "title": "Bytes transferred / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 12 },
   "yaxes": [
    { "format": "Bps" }
   ],
   "targets": [
    {
     "expr": "sum(irate(istio_response_bytes_sum{source_workload_namespace=~\"$namespace\", reporter=\"source\", app=~\"$deploy\"}[$interval]))",
     "legendFormat": "response"
    },
    {
     "expr": "sum(irate(istio_request_bytes_sum{source_workload_namespace=~\"$namespace\", reporter=\"source\", app=~\"$deploy\"}[1m]))",
     "legendFormat": "request"
    }
   ]
  },
  {
   "title": "Disk",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(container_fs_usage_bytes{namespace=~\"$namespace\", container=~\"$deploy\"})",
     "legendFormat": "Usage"
    }
   ]
  }
 ]
}